### ISSUE TITLE
Processing progressbar jumps back

### ISSUE THREAD

**Issue by alexhn** [shmsoft/FreeEed#138]
1) open default project
2) select process locally
3) progressbar percentage will jump back several times during processing.

**Comment by markkerzner** [comment]
That's true, but it should display which zip file it is processing because it jumps back for every zip file. Let us leave this for later, or at least until we discuss possible solutions.

**Comment by alexee** [comment]
Strange is that it jumps back multiple times even within one zip file.

**Comment by markkerzner** [comment]
Ah, that's probably because it finds more files within one zip. But you may be right, a smooth progress would be nice :) Do you want to count the total number of files in all zips, and then base the progress on that? 

Later, when we fix the distributed processing, we can use some kind of global counter as well

**Comment by markkerzner** [comment]
fixed
