### ISSUE TITLE
Export with Attachments / Date Sorting

### ISSUE THREAD

**Issue by DustyArmstrong** [shmsoft/FreeEed#282]
Hi there,

Is it possible to export native with attachments for EML?

Is it also possible to sort results by date? I am unfamiliar with the search format of lucene. 

Thanks again for your work.

**Comment by markkerzner** [comment]
Dusty,

It is possible. But it may be better to email directly with email and add
issues to GitHub.

Thank you

Mark Kerzner, President, Elephant Scale
<https://t.sidekickopen87.com/s3t/c/5/f18dQhb0S7kF8cVZp8W5nLK-W2zGCwVN8Jbw_8QsRtKMpfW-6d0vQdW16gGzC7SyGLk101?te=W3R5hFj26QkH1W3ZVd9v3zd-ghW3F4Fph1JxwY51V3&si=8000000003820840&pi=3b1a0240-ef4a-4e93-ed43-aa959ccea054>
,
713-724-2534 Book a call with me
<https://t.sidekickopen87.com/s3t/c/5/f18dQhb0S7kF8cVZp8W5nLK-W2zGCwVN8Jbw_8QsRtKMpfW-6d0vQdW16gGzC7SyGLk101?te=W3R5hFj4cm2zwW3P4yD541QtgsW4hCPvh43T4P1W3zgDm_3K8RJW3b2k2&si=8000000003820840&pi=3b1a0240-ef4a-4e93-ed43-aa959ccea054>

**Comment by markkerzner** [comment]
FreeED - Advanced Free eDoscovery tool 

https://github.com/shmsoft/FreeEed


** It may sound like a magic fairy tale, but it exists. Although free, it may still be the best for your needs. It may also be the most advanced because it incorporates AI capabilities.
------------------------------------------------------------

Ready to run:
CLICK HERE (https://github.com/shmsoft/FreeEed)

============================================================
** Twitter (https://twitter.com/markkerzner)
** Website (https://github.com/shmsoft/FreeEed)
** LinkedIn (https://www.linkedin.com/in/markkerzner/)

This email was sent to ***@***.*** ***@***.***)
why did I get this? (https://elephantscale.us10.list-manage.com/about?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=fb3dc831e1&c=9a9851459a)     unsubscribe from this list (https://elephantscale.us10.list-manage.com/unsubscribe?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=fb3dc831e1&c=9a9851459a)     update subscription preferences (https://elephantscale.us10.list-manage.com/profile?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=fb3dc831e1&c=9a9851459a)
Scaia AI . 7522 Apache Plume Dr . Houston, TX 77071-2602 . USA

**Comment by markkerzner** [comment]
Webinar
View this email in your browser (https://mailchi.mp/f8be37e0862e/summarization-904728?e=fb3dc831e1)
------------------------------------------------------------
http://elephantscale.com/?utm_campaign=training-followup&utm_medium=email&utm_source=training-followup
Hi ,

https://us02web.zoom.us/webinar/register/7216457127832/WN_b67-hDXPQhShHwgcaFIGdw


** Overview
------------------------------------------------------------

This webinar will show you how to add an automatically generated summary of each document. That's an excellent time-saver in the document review. We will also show you how to detect PII. You cannot be too cautious with PII because of the recent regulatory changes, such as GDPR, CCPA, and LGPD.

For FreeEed fans, it is also a chance to ask about the software's current development state and the roadmap.

See you there!

Date: March 02, Wednesday
Time:  10 AM PST / 12 PM CST / 1 PM EST
Register here (https://us02web.zoom.us/webinar/register/7216457127832/WN_b67-hDXPQhShHwgcaFIGdw)

============================================================
** Twitter (https://twitter.com/scaia11)
** https://scaia.ai/ (https://scaia.ai/)

This email was sent to ***@***.*** ***@***.***)
why did I get this? (https://elephantscale.us10.list-manage.com/about?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=fb3dc831e1&c=020fd1941c)     unsubscribe from this list (https://elephantscale.us10.list-manage.com/unsubscribe?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=fb3dc831e1&c=020fd1941c)     update subscription preferences (https://elephantscale.us10.list-manage.com/profile?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=fb3dc831e1&c=020fd1941c)
Scaia AI . 7522 Apache Plume Dr . Houston, TX 77071-2602 . USA

**Comment by markkerzner** [comment]
Webinar
View this email in your browser (https://mailchi.mp/468c53d9c503/summarization-904744?e=fb3dc831e1)
------------------------------------------------------------
http://elephantscale.com/?utm_campaign=training-followup&utm_medium=email&utm_source=training-followup
Hi ,

https://us02web.zoom.us/webinar/register/7216457127832/WN_b67-hDXPQhShHwgcaFIGdw


** Overview
------------------------------------------------------------

This webinar will show you how to add an automatically generated summary of each document. That's an excellent time-saver in the document review. We will also show you how to detect PII. You cannot be too cautious with PII because of the recent regulatory changes, such as GDPR, CCPA, and LGPD.

For FreeEed fans, it is also a chance to ask about the software's current development state and the roadmap.

See you there!

Date: March 02, Wednesday
Time:  10 AM PST / 12 PM CST / 1 PM EST
Register here (https://us02web.zoom.us/webinar/register/7216457127832/WN_b67-hDXPQhShHwgcaFIGdw)

============================================================
** Twitter (https://twitter.com/scaia11)
** https://scaia.ai/ (https://scaia.ai/)

This email was sent to ***@***.*** ***@***.***)
why did I get this? (https://elephantscale.us10.list-manage.com/about?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=fb3dc831e1&c=3649173285)     unsubscribe from this list (https://elephantscale.us10.list-manage.com/unsubscribe?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=fb3dc831e1&c=3649173285)     update subscription preferences (https://elephantscale.us10.list-manage.com/profile?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=fb3dc831e1&c=3649173285)
Scaia AI . 7522 Apache Plume Dr . Houston, TX 77071-2602 . USA

**Comment by markkerzner** [comment]
News from FreeEed - Casify

View this email in your browser (https://mailchi.mp/5907063372b7/news-from-freeeed-casify?e=fb3dc831e1)
https://getcasify.com/


** Eliminate your stacks of paper files!
------------------------------------------------------------

Brought to you by the FreeEed team! Casify (https://getcasify.com/)  is the only case management software designed specifically for the sole practitioner and small office defense attorney. We wanted to let you know how Casify (https://getcasify.com/)  has helped other attorneys and what we can do to help you:

"The clutter in my office has disappeared, and I never have to search for misplaced files. Instead of carrying my files to court, I only carry my laptop."
Clint Parish
Solo Practitioner & Casify User
Sonora, CA

The team at Casify wants to offer you a free personal training session so you, too, can learn how simple it is to use Casify and leverage it to help streamline your law practice.

Simply reply to this email, and we will arrange a time for a free personal training session with us.

Sincerely,
The Casify Team

============================================================
** (https://getcasify.com/)

This email was sent to ***@***.*** ***@***.***)
why did I get this? (https://elephantscale.us10.list-manage.com/about?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=fb3dc831e1&c=397539b46a)     unsubscribe from this list (https://elephantscale.us10.list-manage.com/unsubscribe?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=fb3dc831e1&c=397539b46a)     update subscription preferences (https://elephantscale.us10.list-manage.com/profile?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=fb3dc831e1&c=397539b46a)
Scaia AI . 7522 Apache Plume Dr . Houston, TX 77071-2602 . USA
