### ISSUE TITLE
Path issues in review after processing

### ISSUE THREAD

**Issue by Corvus4n6** [shmsoft/FreeEed#310]
In v9.1.1 after processing both the included test case and a separate pst file, clicking on "Preview" or Export Image" in the review tool for a document reports "Data do not exist! Please set the 'Files location' property in Case settings page. " in spite of the path to the data being correctly displayed in the Case settings. Clicking the "Export native" button returns the expected data.

**Comment by markkerzner** [comment]
Checking this.

**Comment by markkerzner** [comment]
To get a "Quick preview," you need to do a few things.

1. Request is in the project setting.
![yy](https://user-images.githubusercontent.com/603769/148717038-564616c6-b6f4-4fa0-b7c5-06db82bfa0d3.png)
 
2. Don't expect it everywhere
![q](https://user-images.githubusercontent.com/603769/148717171-bea83397-93d8-4a5e-9abf-cf24b13f20a6.png)
 - it will work in most cases but not in all.
It works on this screen.

3. Export image does work if requested.

This issue is considered closed. I will open an issue to put this in the documentation. Also, will add a lower-priority issue to add HTML preview where possible.

**Comment by markkerzner** [comment]
Resolved and closed.
Mark Kerzner, President, Elephant Scale
<https://t.sidekickopen87.com/s3t/c/5/f18dQhb0S7kF8cVZp8W5nLK-W2zGCwVN8Jbw_8QsRtKMpfW-6d0vQdW16gGzC7SyGLk101?te=W3R5hFj26QkH1W3ZVd9v3zd-ghW3F4Fph1JxwY51V3&si=8000000003820840&pi=a7a4bfe3-3505-47c8-9d31-44c6d6ed5ecd>
,
713-724-2534 Book a call with me
<https://t.sidekickopen87.com/s3t/c/5/f18dQhb0S7kF8cVZp8W5nLK-W2zGCwVN8Jbw_8QsRtKMpfW-6d0vQdW16gGzC7SyGLk101?te=W3R5hFj4cm2zwW3P4yD541QtgsW4hCPvh43T4P1W3zgDm_3K8RJW3b2k2&si=8000000003820840&pi=a7a4bfe3-3505-47c8-9d31-44c6d6ed5ecd>

**Comment by markkerzner** [comment]
FreeED - Advanced Free eDoscovery tool 

https://github.com/shmsoft/FreeEed


** It may sound like a magic fairy tale, but it exists. Although free, it may still be the best for your needs. It may also be the most advanced because it incorporates AI capabilities.
------------------------------------------------------------

Ready to run:
CLICK HERE (https://github.com/shmsoft/FreeEed)

============================================================
** Twitter (https://twitter.com/markkerzner)
** Website (https://github.com/shmsoft/FreeEed)
** LinkedIn (https://www.linkedin.com/in/markkerzner/)

This email was sent to ***@***.*** ***@***.***)
why did I get this? (https://elephantscale.us10.list-manage.com/about?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=267a3233c8&c=9a9851459a)     unsubscribe from this list (https://elephantscale.us10.list-manage.com/unsubscribe?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=267a3233c8&c=9a9851459a)     update subscription preferences (https://elephantscale.us10.list-manage.com/profile?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=267a3233c8&c=9a9851459a)
Scaia AI . 7522 Apache Plume Dr . Houston, TX 77071-2602 . USA

**Comment by markkerzner** [comment]
https://freeeed.org/
https://freeeed.org/


**
------------------------------------------------------------
If I ask you this question - could you use a quick summary of the document instead of reading the whole thing, you would probably answer, "I'd love to, but does it work?" Well, here is an example:

Document

"House Speaker Nancy Pelosi and Democratic leaders have greenlighted a plan to craft legislation that would prohibit members of Congress from trading stock, after months of resistance to a ban by Pelosi, CNBC confirmed Wednesday. At Pelosi's direction, the House Administration Committee is working on drafting the rules, and the legislation is expected to be put up for a vote this year, likely before the November midterm elections."

Summary

"Members of Congress could soon be banned from trading on the stock market."
Imagine how summarization can help you save time by giving you a short, concise summary of documents! Here is a screenshot of FreeEed putting in automatic summaries into its review of an Enron email. It is just a new metadata field, but what a time-saving! The summary is here and the full text is under it, below.

https://github.com/shmsoft/FreeEed
To try FreeEed with summarization, go here:
CLICK HERE (https://github.com/shmsoft/FreeEed)

============================================================
** Twitter (https://twitter.com/markkerzner)
** LinkedIn (https://www.linkedin.com/in/markkerzner/)
** Website (https://freeeed.org/)

This email was sent to ***@***.*** ***@***.***)
why did I get this? (https://elephantscale.us10.list-manage.com/about?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=267a3233c8&c=d205b71123)     unsubscribe from this list (https://elephantscale.us10.list-manage.com/unsubscribe?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=267a3233c8&c=d205b71123)     update subscription preferences (https://elephantscale.us10.list-manage.com/profile?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=267a3233c8&c=d205b71123)
Scaia AI . 7522 Apache Plume Dr . Houston, TX 77071-2602 . USA

**Comment by markkerzner** [comment]
Webinar
View this email in your browser (https://mailchi.mp/f8be37e0862e/summarization-904728?e=267a3233c8)
------------------------------------------------------------
http://elephantscale.com/?utm_campaign=training-followup&utm_medium=email&utm_source=training-followup
Hi ,

https://us02web.zoom.us/webinar/register/7216457127832/WN_b67-hDXPQhShHwgcaFIGdw


** Overview
------------------------------------------------------------

This webinar will show you how to add an automatically generated summary of each document. That's an excellent time-saver in the document review. We will also show you how to detect PII. You cannot be too cautious with PII because of the recent regulatory changes, such as GDPR, CCPA, and LGPD.

For FreeEed fans, it is also a chance to ask about the software's current development state and the roadmap.

See you there!

Date: March 02, Wednesday
Time:  10 AM PST / 12 PM CST / 1 PM EST
Register here (https://us02web.zoom.us/webinar/register/7216457127832/WN_b67-hDXPQhShHwgcaFIGdw)

============================================================
** Twitter (https://twitter.com/scaia11)
** https://scaia.ai/ (https://scaia.ai/)

This email was sent to ***@***.*** ***@***.***)
why did I get this? (https://elephantscale.us10.list-manage.com/about?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=267a3233c8&c=020fd1941c)     unsubscribe from this list (https://elephantscale.us10.list-manage.com/unsubscribe?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=267a3233c8&c=020fd1941c)     update subscription preferences (https://elephantscale.us10.list-manage.com/profile?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=267a3233c8&c=020fd1941c)
Scaia AI . 7522 Apache Plume Dr . Houston, TX 77071-2602 . USA

**Comment by markkerzner** [comment]
News from FreeEed - Casify

View this email in your browser (https://mailchi.mp/5907063372b7/news-from-freeeed-casify?e=267a3233c8)
https://getcasify.com/


** Eliminate your stacks of paper files!
------------------------------------------------------------

Brought to you by the FreeEed team! Casify (https://getcasify.com/)  is the only case management software designed specifically for the sole practitioner and small office defense attorney. We wanted to let you know how Casify (https://getcasify.com/)  has helped other attorneys and what we can do to help you:

"The clutter in my office has disappeared, and I never have to search for misplaced files. Instead of carrying my files to court, I only carry my laptop."
Clint Parish
Solo Practitioner & Casify User
Sonora, CA

The team at Casify wants to offer you a free personal training session so you, too, can learn how simple it is to use Casify and leverage it to help streamline your law practice.

Simply reply to this email, and we will arrange a time for a free personal training session with us.

Sincerely,
The Casify Team

============================================================
** (https://getcasify.com/)

This email was sent to ***@***.*** ***@***.***)
why did I get this? (https://elephantscale.us10.list-manage.com/about?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=267a3233c8&c=397539b46a)     unsubscribe from this list (https://elephantscale.us10.list-manage.com/unsubscribe?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=267a3233c8&c=397539b46a)     update subscription preferences (https://elephantscale.us10.list-manage.com/profile?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=267a3233c8&c=397539b46a)
Scaia AI . 7522 Apache Plume Dr . Houston, TX 77071-2602 . USA
